export const ADDPRODUCT = 'ADDPRODUCT';
export const UPDATEPRODUCT = 'UPDATEPRODUCT';
export const DELEPRODUCT = 'DELEPRODUCT';
export const PLUSPRODUCT = 'PLUSPRODUCT';
export const MINUSPRODUCT = 'MINUSPRODUCT';
export const CLOSEMODELPRODUCTCART = 'CLOSEMODELPRODUCTCART';
export const CLOSEMODELPRODUCTCARTBTN = 'CLOSEMODELPRODUCTCARTBTN';
