export const ADDPRODUCT = 'ADDPRODUCT';
export const PATCHPRODUCT = 'PATCHPRODUCT';
export const PLUSPRODUCT = 'PLUSPRODUCT';
export const MINUSPRODUCT = 'MINUSPRODUCT';
export const DELEPRODUCT = 'DELEPRODUCT';
export const CLOSEMODELPRODUCTCART = 'CLOSEMODELPRODUCTCART';
export const CLOSEMODELPRODUCTCARTBTN = 'CLOSEMODELPRODUCTCARTBTN';
